In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
##USING NUMPY MAKES CALCULATION MUCH MORE FASTER

l = range(1000)
%timeit [i**2 for i in l]

a = np.arange(1000)
%timeit a**2

485 µs ± 32.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.81 µs ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
## 1-D ARRAY USING NUMPY

a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [7]:
print(a.ndim)
print(a.shape)
print(len(a))

1
(4,)
4


In [8]:
## 2-D ARRAY

a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(a.ndim)
print(a.shape)
print(len(a))

2
(2, 3)
2


In [12]:
## 3-D ARRAY

a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
print(a.ndim)
print(a.shape)
print(len(a))

3
(4, 2, 3)
4


In [14]:
##DIFFERENT FUNCTIONS OF CREATING ARRAYS

In [17]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [19]:
a = np.linspace(0, 1, 6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [21]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
a = np.eye(3, 2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [26]:
a = np.diag([1, 2, 3, 4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
print(np.diag(a))

[1 2 3 4]


In [28]:
a = np.random.rand(6)
a

array([0.682728  , 0.7523931 , 0.98624349, 0.86571271, 0.77336379,
       0.3220985 ])

In [31]:
a = np.random.randn(6)
a

array([-1.63641797,  0.57107976,  2.2291079 , -0.7654387 ,  1.24434642,
        0.89359057])

In [32]:
a = np.arange(10)
a.dtype

dtype('int32')

In [34]:
a = np.arange(10, dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
##OTHER DATATYPES

a = np.array([1+2j, 7+3j]) #COMPLEX NUMBER
a
a.dtype

dtype('complex128')

In [37]:
a = np.array([True, False, False, True, True]) #BOOLEAN
a
a.dtype

dtype('bool')

In [38]:
s = np.array(['Ram', 'Robert', 'Rahim']) #STRING
s
s.dtype

dtype('<U6')

In [39]:
##INDEXING

In [40]:
a = np.arange(5)
a[1]

1

In [42]:
a = np.diag([1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:
print(a[2, 2])
a[2, 1] = 6
a

3


array([[1, 0, 0],
       [0, 2, 0],
       [0, 6, 3]])

In [44]:
##SLICING

In [45]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[1:8:2]

array([1, 3, 5, 7])

In [48]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [49]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [50]:
##COPY AND VIEW

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [54]:
np.shares_memory(a,b)

True

In [55]:
b[2] = 11
b

array([ 0,  2, 11,  6,  8])

In [56]:
a

array([ 0,  1,  2,  3, 11,  5,  6,  7,  8,  9])

In [57]:
c = a[::2].copy()
c

array([ 0,  2, 11,  6,  8])

In [58]:
c[2] = 4
c

array([0, 2, 4, 6, 8])

In [59]:
a

array([ 0,  1,  2,  3, 11,  5,  6,  7,  8,  9])

In [61]:
##FANCY INDEXING USING BOOLEAN MASK

a = np.random.randint(0, 20, 15)
a

array([17, 15,  1, 16, 10,  6, 13,  8, 10, 15,  4, 18,  9, 16,  1])

In [62]:
mask = (a%2==0)

a[mask]

array([16, 10,  6,  8, 10,  4, 18, 16])

In [63]:
a[mask] = 100 ##MASK CAN BE USED TO ASSIGN A NEW VALUE TO A SET OF INDICES

a

array([ 17,  15,   1, 100, 100, 100,  13, 100, 100,  15, 100, 100,   9,
       100,   1])

In [64]:
##INDEXING WITH AN ARRAY OF INTEGERS

In [65]:
a = np.arange(10, 100, 10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
a[[2, 3, 2, 4, 2]]

array([30, 40, 30, 50, 30])

In [68]:
a[[8, 6]] = -200

a

array([  10,   20,   30,   40,   50,   60, -200,   80, -200])